objects/ExpenseSelf__c.object
<CustomObject>
    <description>The Expense object was created part of a package</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reimbursed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reimbursed?</label>
        <type>Checkbox</type>
    </fields>
    <label>ExpenseSelf</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExpensesSelf</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseControllerSelf.cls
public with sharing class ExpenseControllerSelf {
    @AuraEnabled
    public static List<ExpenseSelf__c> getExpenses() {
        System.debug('Inside the ExpenseTracker Self');
        // Perform isAccessible() check here
        return [SELECT Id, Name, Amount__c, Client__c, Date__c,
        Reimbursed__c, CreatedDate FROM ExpenseSelf__c];
    }
    
    @AuraEnabled
    public static ExpenseSelf__c saveExpense(ExpenseSelf__c expense) {
    // Perform isUpdateable() check here
    upsert expense;
    return expense;
}
}